BACKUP DATABASE DBAJuniorLab
TO DISK = 'C:\Backups\DBAJuniorLab_Full.bak'
WITH FORMAT,
NAME = 'Full Backup of DBAJuniorLab';
GO

USE master;
GO

ALTER DATABASE DBAJuniorLab
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

RESTORE DATABASE DBAJuniorLab
FROM DISK = 'C:\Backups\DBAJuniorLab_Full.bak'
WITH REPLACE;
GO

ALTER DATABASE DBAJuniorLab
SET MULTI_USER;
GO
